### PR TITLE
Fix error in BieglerKKTSystem's solve for nontrivial scaling

### PR DESCRIPTION
**Pull request by frapac**
cc @amontoison : that explains why we observed a large errors in the KKT benchmark.

### CODE REVIEW

**Comment by amontoison** [comment]
Can we use CUDA 12.3 by default?

**Comment by michel2323** [comment]
I should mention that `] test` fails in CUSOLVERRF with
```
  The current version of CUDA is not supported.
```

**Comment by amontoison** [comment]
Yes, we only support `<= v11.8` or` >= v12.3` for the version of CUDA in `CUSOLVERREF.jl`.

**Comment by frapac** [comment]
> Can we use CUDA 12.3 by default?

Right now, I prefer to keep CUDA runtime 11.8 as the default, as this is the one we are using for our benchmarks. We should be able to replace cusolverRF by CUDSS soon, but I don't know if CUDA 12.3 is available on polaris, which could be a problem for us. 

An alternative solution is to test both for CUDA 11.8 and 12.3 in Argos. But that could be addressed in a separate PR.

**Pull request merged**
